### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by juchiast**
Update to iron 0.6, serde1.0, and most importantly racer 2.1 .

Racer 2.1 requires rust nightly so we might need to update YouCompleteMe's installation script/documentations.

Currently this PR use git dependency for iron-hmac crate. When jwilm/iron-hmac#12 is merged, we can change it.

### CODE REVIEW

**Comment by jwilm** [comment]
Thanks for the PRs! I just merged your other PR to iron-hmac and published a new version. Could you please update the Cargo.toml? I can merge after.

**Comment by jwilm** [comment]
It looks like the Cargo.lock file wasn't committed. Could you please update?

**Comment by juchiast** [comment]
Updated!

**Comment by juchiast** [comment]
lol what is this:
```
error: could not download file from 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256' to '/home/travis/.rustup/tmp/z3ao75ywq5n4rudp_file'
info: caused by: error during download
info: caused by: [28] Timeout was reached

The command "curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y" failed and exited with 1 during .
```

**Comment by juchiast** [comment]
Push again to rerun travis ci.

**Comment by jwilm** [comment]
thanks!

**Pull request merged**
